import type { FileAssociation, LanguageProfile } from "./model";

/** Named Nerd Font glyphs used by built-in file associations and tree chrome. */
export const builtinIcons = new Map<string, string>([
  ["file", "\u{ea7b}"],
  ["folder", "\u{f0256}"],
  ["folder-open", "\u{f0dcf}"],
  ["symlink", "\u{f481}"],
  ["config", "\u{e615}"],
  ["typescript", "\u{e8ca}"],
  ["react", "\u{e7ba}"],
  ["javascript", "\u{e781}"],
  ["json", "\u{eb0f}"],
  ["markdown", "\u{eb1d}"],
  ["css", "\u{e749}"],
  ["csv", "\u{e64a}"],
  ["spreadsheet", "\u{e6a6}"],
  ["profile", "\u{eaf2}"],
  ["database", "\u{e706}"],
  ["document", "\u{f0219}"],
  ["html", "\u{e736}"],
  ["http", "\u{f1d8}"],
  ["astro", "\u{e6b3}"],
  ["template", "\u{f505}"],
  ["pdf", "\u{f1c1}"],
  ["rust", "\u{e7a8}"],
  ["python", "\u{e73c}"],
  ["go", "\u{e724}"],
  ["ruby", "\u{e739}"],
  ["shell", "\u{ebca}"],
  ["toml", "\u{e6b2}"],
  ["yaml", "\u{e8eb}"],
  ["lock", "\u{f023}"],
  ["image", "\u{f1c5}"],
  ["video", "\u{f1c8}"],
  ["java", "\u{e738}"],
  ["kotlin", "\u{e634}"],
  ["groovy", "\u{e775}"],
  ["scala", "\u{e737}"],
  ["gradle", "\u{e7f2}"],
  ["node", "\u{e718}"],
  ["tsconfig", "\u{e69d}"],
  ["bun", "\u{e76f}"],
  ["docker", "\u{e7b0}"],
  ["make", "\u{e673}"],
  ["license", "\u{e60a}"],
  ["git", "\u{e702}"],
  ["readme", "\u{f02d}"],
  ["codeowners", "\u{f510}"],
  ["heroku", "\u{e607}"],
  ["maven", "\u{e674}"],
  ["test", "\u{ea79}"],
  ["storybook", "\u{e8b3}"],
]);

const typescriptServers = ["typescript", "oxlint", "biome"] as const;

/** LSP profiles are separate from file matching so several associations can reuse one route. */
export const builtinLanguages = new Map<string, LanguageProfile>([
  ["css", { languageId: "css", servers: ["biome"] }],
  ["graphql", { languageId: "graphql", servers: ["biome"] }],
  ["json", { languageId: "json", servers: ["json", "biome"] }],
  ["jsonc", { languageId: "jsonc", servers: ["json", "biome"] }],
  [
    "python",
    {
      languageId: "python",
      servers: [{ firstOf: ["ty", "basedpyright"] }, "ruff"],
    },
  ],
  ["rust", { languageId: "rust", servers: ["rust-analyzer"] }],
  ["javascript", { languageId: "javascript", servers: typescriptServers }],
  ["javascriptreact", { languageId: "javascriptreact", servers: typescriptServers }],
  ["typescript", { languageId: "typescript", servers: typescriptServers }],
  ["typescriptreact", { languageId: "typescriptreact", servers: typescriptServers }],
  ["yaml", { languageId: "yaml", servers: ["yaml"] }],
]);

const iconExtensions = (
  name: string,
  icon: string,
  extensions: readonly string[],
): readonly [string, FileAssociation] => [name, { extensions, icon }];

/** Built-in file associations. Later entries win ties at the same match specificity. */
export const builtinFiles = new Map<string, FileAssociation>([
  ["language-css", { extensions: ["css"], language: "css" }],
  ["language-graphql", { extensions: ["graphql"], language: "graphql" }],
  ["language-json", { extensions: ["json"], language: "json" }],
  ["language-jsonc", { extensions: ["jsonc"], language: "jsonc" }],
  ["language-python", { extensions: ["py", "pyi"], language: "python" }],
  ["language-rust", { extensions: ["rs"], language: "rust" }],
  ["language-javascript", { extensions: ["js", "mjs", "cjs"], language: "javascript" }],
  ["language-javascriptreact", { extensions: ["jsx"], language: "javascriptreact" }],
  ["language-typescript", { extensions: ["ts", "mts", "cts"], language: "typescript" }],
  ["language-typescriptreact", { extensions: ["tsx"], language: "typescriptreact" }],
  ["language-yaml", { extensions: ["yaml", "yml"], language: "yaml" }],

  ["syntax-env", { filenames: [".env"], syntax: "dotenv" }],
  ["syntax-npmrc", { filenames: [".npmrc"], syntax: "ini" }],
  ["syntax-prettierrc", { filenames: [".prettierrc"], syntax: "jsonc" }],
  ["syntax-gradle", { globs: ["*.gradle"], syntax: "groovy" }],
  ["syntax-ruby-template", { globs: ["*.rb.tmpl"], syntax: "ruby" }],

  iconExtensions("icon-typescript", "typescript", ["ts", "mts", "cts"]),
  iconExtensions("icon-react", "react", ["tsx", "jsx"]),
  iconExtensions("icon-javascript", "javascript", ["js", "mjs", "cjs"]),
  iconExtensions("icon-json", "json", ["json"]),
  iconExtensions("icon-markdown", "markdown", ["md", "mdx"]),
  iconExtensions("icon-css", "css", ["css"]),
  iconExtensions("icon-csv", "csv", ["csv"]),
  iconExtensions("icon-spreadsheet", "spreadsheet", ["xls", "xlsx"]),
  iconExtensions("icon-profile", "profile", ["cpuprofile"]),
  iconExtensions("icon-database", "database", ["sql"]),
  iconExtensions("icon-document", "document", ["txt"]),
  iconExtensions("icon-html", "html", ["html"]),
  iconExtensions("icon-http", "http", ["http"]),
  iconExtensions("icon-astro", "astro", ["astro"]),
  iconExtensions("icon-template", "template", ["mako"]),
  iconExtensions("icon-pdf", "pdf", ["pdf"]),
  iconExtensions("icon-rust", "rust", ["rs"]),
  iconExtensions("icon-python", "python", ["py"]),
  iconExtensions("icon-go", "go", ["go"]),
  iconExtensions("icon-ruby", "ruby", ["rb"]),
  iconExtensions("icon-shell", "shell", ["sh", "bash", "zsh"]),
  iconExtensions("icon-toml", "toml", ["toml"]),
  iconExtensions("icon-config", "config", ["conf", "ini"]),
  iconExtensions("icon-yaml", "yaml", ["yml", "yaml"]),
  iconExtensions("icon-lock", "lock", ["lock"]),
  iconExtensions("icon-image", "image", ["png", "jpg", "jpeg", "gif", "webp", "ico", "svg"]),
  iconExtensions("icon-video", "video", ["mp4", "mov", "mkv", "webm", "avi"]),
  iconExtensions("icon-java", "java", ["java", "jar", "class"]),
  iconExtensions("icon-kotlin", "kotlin", ["kt", "kts"]),
  iconExtensions("icon-groovy", "groovy", ["groovy", "gvy"]),
  iconExtensions("icon-scala", "scala", ["scala", "sc"]),
  iconExtensions("icon-gradle", "gradle", ["gradle"]),

  ["icon-node-filename", { filenames: ["package.json"], icon: "node" }],
  ["icon-tsconfig-filename", { filenames: ["tsconfig.json"], icon: "tsconfig" }],
  ["icon-bun-filenames", { filenames: ["bun.lock", "bunfig.toml"], icon: "bun" }],
  ["icon-dockerfile", { filenames: ["dockerfile"], icon: "docker" }],
  ["icon-makefile", { filenames: ["makefile"], icon: "make" }],
  ["icon-gitignore", { filenames: [".gitignore"], icon: "git" }],
  ["icon-env", { filenames: [".env"], icon: "config" }],
  ["icon-readme", { filenames: ["readme.md", "readme"], icon: "readme" }],
  ["icon-codeowners", { filenames: ["codeowners"], icon: "codeowners" }],
  ["icon-procfile", { filenames: ["procfile"], icon: "heroku" }],
  [
    "icon-gradle-filenames",
    {
      filenames: [
        "build.gradle",
        "settings.gradle",
        "build.gradle.kts",
        "settings.gradle.kts",
        "gradle.properties",
        "gradle-wrapper.properties",
        "gradlew",
        "gradlew.bat",
      ],
      icon: "gradle",
    },
  ],
  ["icon-maven-filename", { filenames: ["pom.xml"], icon: "maven" }],
  [
    "icon-license",
    {
      filenames: [
        "copying",
        "unlicense",
        "notice",
        "mit",
        "isc",
        "apache-2.0",
        "bsd-2-clause",
        "bsd-3-clause",
        "gpl-2.0",
        "gpl-3.0",
        "lgpl-3.0",
        "agpl-3.0",
        "mpl-2.0",
      ],
      globs: ["license*", "licence*", "cc-by*", "cc0*"],
      icon: "license",
    },
  ],
  ["icon-ruby-template", { globs: ["*.rb.tmpl"], icon: "ruby" }],
  [
    "icon-test",
    {
      globs: ["*.test.*", "*.spec.*", "*_test.*", "*_spec.*", "*.cy.*", "test_*.*"],
      icon: "test",
    },
  ],
  ["icon-storybook", { globs: ["*.stories.*", "*.story.*"], icon: "storybook" }],
  ["icon-dotfiles", { dotfiles: true, icon: "config" }],
]);
