import type { Theme } from "./tokens";

// Shared hexes are intentionally repeated across tokens (e.g. the green in
// Diff.addedSign / stage.staged / kind.added / success): each role may diverge
// In another theme, so call sites must not assume they match
export const darkTheme: Theme = {
  accent: { dim: "#8a3a6e", primary: "#ff4fb8" },
  border: { focused: "#ff4fb8", unfocused: "#27272a" },
  diff: {
    addedBg: "#102a1c",
    addedLineNumberBg: "#0d2117",
    addedSign: "#3ddc84",
    lineNumberFg: "#52525b",
    removedBg: "#32131f",
    removedLineNumberBg: "#260f18",
    removedSign: "#ff5c8a",
  },
  kind: {
    added: "#3ddc84",
    deleted: "#ff5c8a",
    modified: "#fbbf24",
    renamed: "#c084fc",
    untracked: "#3ddc84",
  },
  scrollbar: { thumb: "#3f3f46", track: "#09090b" },
  severity: {
    error: "#ff5c8a",
    errorGutterBg: "#52141f",
    info: "#6aa9ff",
    infoGutterBg: "#16263f",
    warning: "#fbbf24",
    warningGutterBg: "#4a3a10",
  },
  stage: {
    mixed: "#fb923c",
    staged: "#3ddc84",
    unstaged: "#fbbf24",
    untracked: "#a1a1aa",
  },
  success: "#3ddc84",
  surface: { base: "#09090b", cursor: "#3a1530", panel: "#111113" },
  // The syntax theme lives at the semantic-group level; expandCaptureStyles
  // Aliases the dotted captures each grammar actually emits onto these entries
  syntax: {
    "attribute": { fg: "#f0abfc", italic: true },
    "boolean": { bold: true, fg: "#fbbf24" },
    "character": { fg: "#86efac" },
    "comment": { dim: true, fg: "#71717a" },
    "comment.documentation": { fg: "#71717a", italic: true },
    "constant": { fg: "#fbbf24" },
    "constant.builtin": { bold: true, fg: "#fbbf24" },
    "constructor": { fg: "#f0abfc" },
    "default": { fg: "#e4e4e7" },
    "escape": { fg: "#f5a3d7" },
    "function": { fg: "#67e8f9" },
    "function.builtin": { bold: true, fg: "#67e8f9" },
    "function.test": { bold: true, fg: "#f0abfc" },
    "function.test.assert": { bold: true, fg: "#67e8f9" },
    "function.test.suite": { bold: true, fg: "#ff4fb8" },
    "keyword": { bold: true, fg: "#ff4fb8" },
    "label": { fg: "#93c5fd" },
    "markup": { fg: "#e4e4e7" },
    "markup.heading": { bold: true, fg: "#ff4fb8" },
    "markup.heading.1": { bold: true, fg: "#ff4fb8", underline: true },
    "markup.heading.2": { bold: true, fg: "#ff4fb8" },
    "markup.heading.3": { fg: "#ff4fb8" },
    "markup.heading.4": { fg: "#ff4fb8" },
    "markup.heading.5": { fg: "#ff4fb8" },
    "markup.heading.6": { fg: "#ff4fb8" },
    "markup.italic": { fg: "#e4e4e7", italic: true },
    "markup.link": { fg: "#67e8f9", underline: true },
    "markup.link.bracket.close": { fg: "#67e8f9" },
    "markup.link.label": { fg: "#93c5fd" },
    "markup.list": { fg: "#ff4fb8" },
    "markup.list.checked": { fg: "#86efac" },
    "markup.list.unchecked": { fg: "#fbbf24" },
    "markup.quote": { fg: "#a1a1aa", italic: true },
    "markup.raw": { fg: "#86efac" },
    "markup.strikethrough": { dim: true, fg: "#71717a" },
    "markup.strong": { bold: true, fg: "#e4e4e7" },
    "module": { fg: "#93c5fd" },
    "number": { fg: "#fbbf24" },
    "operator": { fg: "#f5a3d7" },
    "property": { fg: "#93c5fd" },
    "punctuation": { fg: "#a1a1aa" },
    "punctuation.special": { fg: "#f5a3d7" },
    "string": { fg: "#86efac" },
    "string.escape": { fg: "#f5a3d7" },
    "string.regexp": { fg: "#f5a3d7" },
    "string.special.key": { fg: "#93c5fd" },
    "tag": { fg: "#fda4af" },
    "tag.attribute": { fg: "#f0abfc", italic: true },
    "type": { fg: "#f0abfc" },
    "type.builtin": { bold: true, fg: "#f0abfc" },
    "variable": { fg: "#e4e4e7" },
    "variable.builtin": { fg: "#f0abfc" },
    "variable.member": { fg: "#93c5fd" },
  },
  text: {
    faint: "#52525b",
    muted: "#71717a",
    primary: "#e4e4e7",
    secondary: "#a1a1aa",
    selected: "#ffffff",
    strong: "#d4d4d8",
  },
};
