/**
 * Regenerate the README screenshots by driving the real sideye binary through VHS (a headless
 * terminal that renders Nerd Font icons correctly), so the icons and theme match a real terminal.
 * Each screen is a generated .tape that launches sideye, drives it to a state with keystrokes, and
 * screenshots it. The problems/diagnostics shots need a changed file with diagnostics, so a temp
 * errorful file is created in src/ around those runs only.
 *
 * Run on a clean checkout (`bun run screenshots`) so the tree and diff are representative;
 * uncommitted files would show up in the captured tree. Requires `vhs` on PATH (brew install vhs)
 * and a Nerd Font installed for the file-type icons. Pass screen names to shoot a subset, e.g. `bun
 * run screenshots find problems`.
 */
import { rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";

const REPO = resolve(import.meta.dir, "..");
const BUN = process.execPath;
const VHS = "vhs";
const OUT = "assets/screenshots";
const TAPES = resolve(tmpdir(), "sideye-screenshots");
/** A few commits back so the diff and tree show several changed source files, not just a dep bump. */
const BASE_REF = "HEAD~3";
/**
 * Inside src/ so it falls under tsconfig's include and typescript-language-server reports the type
 * error alongside oxlint's unused-symbol findings.
 */
const FIXTURE = `${REPO}/src/_diagnostics-demo.ts`;

const header = [
  "Set Shell zsh",
  'Set FontFamily "FiraCode Nerd Font Mono"',
  "Set FontSize 28",
  "Set Width 2560",
  "Set Height 1520",
  "Set Padding 0",
  "Set Margin 0",
  "Set TypingSpeed 0",
].join("\n");

const launch = [
  "Hide",
  `Type "${BUN} run src/main.tsx ${BASE_REF}"`,
  "Enter",
  "Sleep 3s",
  "Show",
  "Sleep 500ms",
].join("\n");

/**
 * Open a real source-file diff (the palette focuses the viewer on select), so the main and find
 * shots feature code rather than the default docs file.
 */
const openDiffView = ["Ctrl+P", 'Type "DiffView"', "Sleep 400ms", "Enter", "Sleep 800ms"].join(
  "\n",
);

/**
 * One entry per README screenshot. `steps` run after the app is up; the end state is captured.
 * `fixture: true` marks screens that need the temporary diagnostics file planted first.
 */
const screens = [
  { name: "sideye", steps: openDiffView },
  { name: "worktree-picker", steps: ['Type "w"', "Sleep 800ms"].join("\n") },
  { name: "go-to-file", steps: ["Ctrl+P", 'Type "diff"', "Sleep 600ms"].join("\n") },
  {
    // Enter commits the find so the title shows the N/M match counter with highlights live.
    name: "find",
    steps: [openDiffView, 'Type "/"', 'Type "import"', "Sleep 300ms", "Enter", "Sleep 600ms"].join(
      "\n",
    ),
  },
  { name: "search", steps: ["Ctrl+F", 'Type "Effect"', "Sleep 1200ms"].join("\n") },
  {
    // Open an unchanged file: plain syntax-highlighted source, no diff gutters.
    name: "read-only",
    steps: ["Ctrl+P", 'Type "process"', "Sleep 400ms", "Enter", "Sleep 800ms"].join("\n"),
  },
  { name: "keys", steps: ['Type "?"', "Sleep 600ms"].join("\n") },
  {
    // Open the fixture, open the panel, then wait out tsserver's project load (slower than oxlint).
    fixture: true,
    name: "problems",
    steps: [
      "Ctrl+P",
      'Type "diagnostics-demo"',
      "Sleep 400ms",
      "Enter",
      "Sleep 800ms",
      'Type "p"',
      "Sleep 16s",
    ].join("\n"),
  },
  {
    // Panel closed so the inline cue is the focus; cursor lands on the type-error line.
    fixture: true,
    name: "viewer-diagnostics",
    steps: [
      "Ctrl+P",
      'Type "diagnostics-demo"',
      "Sleep 400ms",
      "Enter",
      "Sleep 800ms",
      "Down",
      "Down",
      "Down",
      "Down",
      "Sleep 16s",
    ].join("\n"),
  },
];

function tapeFor(screen: (typeof screens)[number]) {
  return [
    `# ${screen.name}.png — generated by script/screenshots.ts`,
    header,
    launch,
    screen.steps,
    `Screenshot ${OUT}/${screen.name}.png`,
    "",
  ].join("\n\n");
}

async function run(cmd: string, cmdArgs: string[]) {
  const proc = Bun.spawn([cmd, ...cmdArgs], {
    cwd: REPO,
    stdio: ["inherit", "inherit", "inherit"],
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`${cmd} exited ${code}`);
  }
}

async function shoot(screen: (typeof screens)[number]) {
  await Bun.write(`${TAPES}/${screen.name}.tape`, tapeFor(screen));
  console.log(`▶ ${screen.name}`);
  await run(VHS, [`${TAPES}/${screen.name}.tape`]);
}

/** Sync so it can run from a signal handler before exit, not just the finally path. */
function removeFixture() {
  rmSync(FIXTURE, { force: true });
}

const only = new Set(Bun.argv.slice(2));
const unknown = [...only].filter((name) => !screens.some((screen) => screen.name === name));
if (unknown.length > 0) {
  console.warn(
    `ignoring unknown screen name(s): ${unknown.join(", ")} — known: ${screens.map((screen) => screen.name).join(", ")}`,
  );
}

const wanted = screens.filter((screen) => only.size === 0 || only.has(screen.name));
const standalone = wanted.filter((screen) => !screen.fixture);
const fixtured = wanted.filter((screen) => screen.fixture);

for (const screen of standalone) {
  // oxlint-disable-next-line no-await-in-loop -- vhs spawns a headless terminal; runs must be sequential
  await shoot(screen);
}

if (fixtured.length > 0) {
  /**
   * Diagnostics only exist for a changed file, so plant one. Lead with clean exported lines (no
   * findings, plain gutter) so the flagged lines' severity-colored gutter numbers stand out, then
   * tsc type errors (number = string) and oxc unused-symbol findings.
   */
  await Bun.write(
    FIXTURE,
    [
      "export function double(n: number) {",
      "  return n * 2",
      "}",
      "",
      'export const label: number = "oops"',
      "const ignored = double(label)",
      "const count: string = 42",
      "function helper(unusedParam: number) {}",
      "",
    ].join("\n"),
  );
  // A Ctrl-C mid-shoot skips the finally, so also delete the fixture on interruption.
  for (const signal of ["SIGINT", "SIGTERM"] as const) {
    process.once(signal, () => {
      removeFixture();
      process.exit(130);
    });
  }
  try {
    for (const screen of fixtured) {
      // oxlint-disable-next-line no-await-in-loop -- vhs spawns a headless terminal; runs must be sequential
      await shoot(screen);
    }
  } finally {
    removeFixture();
    console.log("cleaned up diagnostics fixture");
  }
}

console.log("done");
